### ISSUE TITLE
X-9-Y clarifications from BGG thread

### ISSUE THREAD

**Issue by JVor** [504rules/504rules.github.io#14]
Update the changes from https://www.boardgamegeek.com/thread/1459500/clarification-determining-income-worlds-x-9-y. I hope I got all changes correctly, it gets rather complicated:

19Y, section 3H: drop the last sentence from the first paragraph ("Finally, the company places all delivered goods into the general storage."), maybe replace it with "Afterwards, the goods remain in front of the company card."

29Y, section 3D: replace "he places **that resident** directly on top of the matching city card" with "he places **a settlement** on top of the matching city card"
29Y, section 3H: replace "... each time it places **a new resident** on 1 or more city cards ..." with "... **a settlement** ..."

89Y (Y > 1), section 3H: drop the first paragraph, instead fill in the following:
"The company may sell goods already produced in its plants It may sell 1 good to each of its trading houses (up to 2 goods to the headquarters in its capital). Afterwards, the goods remain in front of the company card."

The income example also doesn't work any more for this combination.

**Comment by Arachnid** [comment]
Thanks for the corrections, applied.

World 891 seems ambiguous; does this look correct to you for the first paragraph of Phase 3 H?

"The company may sell goods already delivered to its trading houses. It may sell 1 good to each of its trading houses (up to 2 goods to the headquarters in its capital). Afterwards, the goods remain on the trading houses."

**Comment by someknave** [comment]
Just looking at the x9y rule sets and I am surprised at how well they read. I specifically looked at 697 as it seemed like a particularly tricky one. 

Some notes: 
It inconsistently uses the words player and stock company in the main rules explanation. This isn't too bad but could lead to some confusion. 
More importantly the final scoring reads: 
Quote:
The players get victory points (VP) for each of their tiles regarding to the majority table, see the table and example for Final Scoring.
The player with the most VP wins the game. In case of a tie, the tied player with the most residents on tiles with his roads wins.
First, the players determine the victory points (VP) of the 5 stock companies. Second, the best stock companies (having the most VP) get bonus VP, see table Bonus VP at the Final Scoring.
The players get VP for each of their shares equal to the total number of VP of the matching stock companies (the president's share counts twice!).
The player with the most VP wins the game! In case of a tie, all tied players share the victory.
The players get additional victory points (VP) for majorities during the final scoring, see table and example of the Final Scoring.

This needs a little work. I have reordered the rules below:
First, the players determine the victory points (VP) of the 5 stock companies. 
_The ~~players~~ **companies** get victory points (VP) for each of their tiles regarding to the majority table, see the table and example for Final Scoring._ 
~~The player with the most VP wins the game. In case of a tie, the tied player with the most residents on tiles with his roads wins.~~
_The ~~players~~ **companies** get additional victory points (VP) for majorities during the final scoring, see table and example of the Final Scoring._
Second, the best stock companies (having the most VP) get bonus VP, see table Bonus VP at the Final Scoring. **In case of a tie, add the VP of the respective places for the tied companies and divide them (round up).**
The players get VP for each of their shares equal to the total number of VP of the matching stock companies (the president's share counts twice!).
The player with the most VP wins the game! In case of a tie, all tied players share the victory.

I understand that this could be difficult to implement consistently for all x9y games. 

edit: this also highlights a minor issue with the endgame scoring for xy7 which adds the majority points after the tiebreaker is determined. this is also a bit of a quibble rather than an issue.
This is also an issue for xy9 games.
I think that the final scoring needs a different template if module 9 is in position II or III.

**Comment by someknave** [comment]
I believe that this issue has been resolved
